DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'RolUsuario') THEN
    CREATE TYPE "RolUsuario" AS ENUM ('SUPERADMIN', 'ADMINISTRADOR', 'SUPERVISOR', 'RECEPCIONISTA');
  END IF;
END $$;

ALTER TABLE "Usuario" ADD COLUMN IF NOT EXISTS "rol" "RolUsuario" NOT NULL DEFAULT 'RECEPCIONISTA';
